name: Deploy to Server

on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write private key to file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/private_key
          chmod 600 private_key

- name: Deploy via SSH
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USER }}
    key_path: /tmp/private_key
    port: 22
    debug: true
    script: |
      echo "✅ CONNECTED"
      rm -rf /var/www/html/*
      git clone https://github.com/LSchouG/Website.git temp-site
      cp -r temp-site/* /var/www/html/
      rm -rf temp-site
      sudo chown -R www-data:www-data /var/www/html
      sudo systemctl restart nginx
