name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decode and save SSH private key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 -d > id_ed25519
        chmod 644 id_ed25519

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 91.98.24.160
        username: larssg
        key_path: ./id_ed25519
        port: 22
        script: |
          echo "✅ CONNECTED"
          rm -rf /var/www/html/*
          git clone https://github.com/LSchouG/Website.git temp-site
          cp -r temp-site/* /var/www/html/
          rm -rf temp-site
          sudo chown -R www-data:www-data /var/www/html
          sudo systemctl restart nginx
